### ISSUE TITLE
An error occurred while executing the plugin.

### ISSUE THREAD

**Issue by dockcy** [Doujiang2333/AFinChat#3]
This plugin shows the following error , maybe somethin run with the code or network.
`An error occurred while executing the plugin.`

**Comment by Doujiang2333** [comment]
后台确实有些问题，最近频繁崩溃，可能是服务开的有点多了，这周修复一下

**Comment by Doujiang2333** [comment]
Fixed, maybe.

Contact me if it goes wrong again
